// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace RustFractals
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "rust_fractal";





        [DllImport(__DllName, EntryPoint = "test", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint test();

        /// <summary>
        ///  # Safety
        ///
        ///  len must be width * height
        ///  this is a test
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mandelbrot_baseline_render_u32", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void mandelbrot_baseline_render_u32(float center_x, float center_y, ulong zoom, int width_px, int height_px, int max_iter, uint* dst, nuint dst_len);


    }



}
